import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNavbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "./providers";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const savedTheme = (await cookies()).get("theme")?.value;
  const initialTheme = savedTheme === "light" ? "light" : "dark";
  const isDark = initialTheme === "dark";

  return (
    <html
      lang="en"
      data-theme={initialTheme}
      className={`${geistSans.variable} ${geistMono.variable} ${isDark ? "dark" : ""} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var match = document.cookie.match(/(?:^|; )theme=(light|dark)(?:;|$)/);
                  var cookieTheme = match ? match[1] : null;
                  var theme = localStorage.getItem('theme') || cookieTheme || '${initialTheme}';
                  localStorage.setItem('theme', theme);
                  document.cookie = 'theme=' + theme + '; path=/; max-age=31536000; samesite=lax';
                  document.documentElement.setAttribute('data-theme', theme);
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })()
            `
          }}
        />
      </head>
      <body className="min-h-full flex flex-col bg-background text-foreground transition-colors duration-300">
        <Providers initialTheme={initialTheme}>
          <MainNavbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
